import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { SelectionProvider } from "@/contexts/SelectionContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SelectionProvider>
            {children}
            <Toaster
              position="bottom-right"
              toastOptions={{
                style: {
                  background: "#111",
                  color: "#fff",
                  padding: "16px 24px",
                  fontSize: "16px",          // más grande
                  minWidth: "280px",         // más ancho
                  borderRadius: "8px",       // esquinas redondeadas
                },
                success: {
                  icon: "✅",
                  style: {
                    background: "#22c55e",
                    color: "white",
                  },
                },
                error: {
                  icon: "❌",
                  style: {
                    background: "#ef4444",
                    color: "white",
                  },
                },
              }}
            />
          </SelectionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
