name: Run Tests

on:
  push:
    branches:
        - main
        - feature*
        - fix*
  pull_request:
    branches:
        - main
        - feature*
        - fix*

jobs:
  test:
    runs-on: ubuntu-latest      

    env:
      MONGO_URI: "mongodb://localhost:27017"
      DB_NAME: "test_database"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          pytest -v
